spring.application.name=biblioteca-jogos
# URL de conexão (substitua 'nome_do_seu_banco' pelo nome real)
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecas_jogos
spring.datasource.username=caigods
spring.datasource.password=caigods

# Driver e Dialeto (O Spring Boot geralmente detecta sozinho, mas é bom definir)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Estratégia de atualização do banco (update apenas atualiza o esquema sem apagar dados)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 #Projeto para testarem, nao tem problema expor a chave
jwt.secret=83c5a57c4c9798005baa1f775b16857d684409ed36e45e198fccebdab9b7ae9c




